import { CULINARYPOSTS } from "./CULINARYPOSTS";
import { GEARPOSTS } from "./GEARPOSTS";
import { HITCHHIKINGPOSTS } from "./HITCHHIKINGPOSTS";
import { VOLUNTEERPOSTS } from "./VOLUNTEERPOSTS";

export const ALLPOSTS = [...CULINARYPOSTS, ...GEARPOSTS, ...HITCHHIKINGPOSTS, ...VOLUNTEERPOSTS];
